name: solution_challenge
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  json_annotation:
  http:
  marquee:
  auto_size_text:
  flutter_webview_plugin:
  url_launcher:
  fancy_drawer:
  flutter_email_sender:  
  simple_animations:
  geolocator: ^5.1.3
  lottie: ^0.6.0  
  firebase_core: "^0.5.0"
  cloud_firestore: ^0.14.1
  image_picker: 
  firebase_storage:
  get:   
  cached_network_image:
  google_maps_flutter:
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Icons/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Subjects/ds_algo/Algorithms.jpg
    - assets/Subjects/computer_networks/Data Link Layer.jpg
    - assets/Subjects/computer_networks/Network Layer.jpg
    - assets/Subjects/computer_networks/Application Layer.jpg
    - assets/Subjects/computer_networks/Transport Layer.jpg
    - assets/Subjects/ds_algo/Data Structures.jpg
    - assets/Subjects/operating_system/Process.jpg
    - assets/Subjects/operating_system/Process Scheduling.jpg
    - assets/Subjects/dbms/Introduction.jpg
    - assets/Subjects/dbms/ER Model.jpg
    - assets/Subjects/dbms/Relation Model.jpg
    - assets/Subjects/dbms/Relational Database.jpg
    - assets/Subjects/dbms/File Structure.jpg
    - assets/Subjects/dbms/Indexing & Hashing.jpg
    - assets/Subjects/dbms/Concurrency.jpg
    - assets/Subjects/dbms/Backup Recovery.jpg
    - assets/Subjects/operating_system/Scheduling Algorithms.jpg
    - assets/Subjects/operating_system/Virtual Memory.jpg
    - assets/Subjects/operating_system/Other topics.jpg
    - assets/43885-laptop-working.json
    - assets/Icons/study.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Fonts/Montserrat-Regular.ttf
        - asset: assets/Fonts/Montserrat-Italic.ttf
        - asset: assets/Fonts/Montserrat-ExtraBold.ttf
        - asset: assets/Fonts/Montserrat-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
